language: node_js
node_js:
  - "4.0"
cache:
  directories:
  - node_modules
env:
  global:
  - GH_REF: github.com/hook/champions.git
after_success:
  - "${TRAVIS_PULL_REQUEST} || npm run deploy"
sudo: false
