language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm prune
after_success:
  - "${TRAVIS_PULL_REQUEST} || npm run deploy"
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    - GH_REF: github.com/hook/champions.git
