language: node_js
node_js:
  - "7"
dist:
  - "xenial"
os:
  - "linux"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8
    - GH_REF: github.com/hook/champions.git

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy
