language: node_js
node_js:
  - "4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - node_modules
env:
  - CXX=g++-4.8
  global:
  - GH_REF: github.com/hook/champions.git
before_install:
- npm prune
after_success:
  - "${TRAVIS_PULL_REQUEST} || npm run deploy"
sudo: false
