language: node_js
node_js:
  - "7"
dist:
  - "xenial"
os:
  - "linux"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy || false'
env:
  - CXX=g++-4.8
  global:
    - GH_REF: github.com/hook/champions.git
branches:
  only:
    - master
